/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.scenes;

import fmm.classesauxiliares.Produto;
import fmm.classesauxiliares.ProdutoController;
import java.awt.Cursor;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 2aimaq20
 */
public class AlterProduct extends javax.swing.JFrame {
    private Produto p;
    /**
     * Creates new form AlterProduct
     */
    public AlterProduct() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png")).getImage());
        name.setText(name.getText()+" "+Inventory.pAlter.getNome());
        price.setText(price.getText()+" R$ "+Inventory.pAlter.getPreco());
        quant.setText(quant.getText()+" "+Inventory.pAlter.getQuant());
        p = new Produto(Inventory.pAlter.getNome(),Inventory.pAlter.getQuant(),Inventory.pAlter.getPreco(),Inventory.pAlter.getId());
        newPrice.setText("0");
        
        
        newName.setText(Inventory.pAlter.getNome());
        newPrice.setText(Float.toString(Inventory.pAlter.getPreco()));
        quant1.setValue(Inventory.pAlter.getQuant());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quant = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        quant1 = new javax.swing.JSpinner();
        newName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        newPrice = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        lblAlter = new javax.swing.JLabel();
        bgAP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Sale");
        setMaximumSize(new java.awt.Dimension(739, 459));
        setMinimumSize(new java.awt.Dimension(739, 459));
        setPreferredSize(new java.awt.Dimension(739, 459));
        setResizable(false);
        getContentPane().setLayout(null);

        quant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        quant.setForeground(new java.awt.Color(255, 255, 255));
        quant.setText("Quantidade:");
        getContentPane().add(quant);
        quant.setBounds(40, 160, 470, 40);

        price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Preço: ");
        getContentPane().add(price);
        price.setBounds(40, 110, 470, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Novo Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 210, 80, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nova Quantidade");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 290, 100, 20);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/save_icon.png"))); // NOI18N
        save.setToolTipText("Alterar Dados");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(360, 360, 60, 64);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/volta_icon.png"))); // NOI18N
        back.setToolTipText("Voltar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 20, 64, 64);

        quant1.setToolTipText("Campo para alterar Quantidade");
        quant1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quant1StateChanged(evt);
            }
        });
        getContentPane().add(quant1);
        quant1.setBounds(290, 310, 190, 30);

        newName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newName.setToolTipText("Campo para alterar nome");
        getContentPane().add(newName);
        newName.setBounds(70, 230, 300, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Novo Preço");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 210, 80, 20);

        newPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newPrice.setToolTipText("Campo para alterar Preço");
        getContentPane().add(newPrice);
        newPrice.setBounds(410, 230, 290, 40);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Nome: ");
        getContentPane().add(name);
        name.setBounds(40, 60, 470, 40);

        lblAlter.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblAlter.setForeground(new java.awt.Color(255, 255, 255));
        lblAlter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlter.setText("Alterar Produto");
        getContentPane().add(lblAlter);
        lblAlter.setBounds(200, 10, 320, 50);

        bgAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/bg_tm_right.jpg"))); // NOI18N
        getContentPane().add(bgAP);
        bgAP.setBounds(0, 0, 740, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quant1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quant1StateChanged
        if(Integer.valueOf(String.valueOf(quant1.getValue()))<0){
            quant1.setValue(0);
        }
        else{
            Inventory.pAlter.setQuant(Integer.valueOf(String.valueOf(quant1.getValue())));
        }
    }//GEN-LAST:event_quant1StateChanged

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        if(newName.getText().equals("")&&newPrice.getText().equals("")&&Integer.valueOf(String.valueOf(quant1.getValue()))==0){
            JOptionPane.showMessageDialog(this, "Insert at least one field!");
        }
        else{
                
                
                if(newPrice.getText().contains(",")){
                    newPrice.setText(newPrice.getText().replace(",","."));
                    System.out.println(newPrice.getText());
                }
                float precof=  Float.parseFloat(newPrice.getText());
                int quantf = Integer.valueOf(String.valueOf(quant1.getValue()));
               
                
                   int e = JOptionPane.showConfirmDialog(this, "Deseja alterar?");
                   if(e==0){
                     try{
                         System.out.println("Id: "+Inventory.pAlter.getId());
                       if(ProdutoController.alterProductALL(newName.getText(),precof,quantf,Inventory.pAlter.getId()))
                       {
                           JOptionPane.showMessageDialog(this, "Alterado!","Alerta",0);
                            Inventory af;
                                try {
                                     af = new Inventory();
                                     af.setLocation(getLocation());
                                  dispose();
                                   af.setVisible(true);
                                 } catch (ClassNotFoundException|SQLException ex) {
                                      System.out.println(ex);
                                  }
                       }else JOptionPane.showMessageDialog(this, "Não alterado!","Alerta",0);
                      } catch (ClassNotFoundException|SQLException ex) {
                            System.out.println(ex);
                        }
                     
                   }
                
                }
        
        
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saveMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
            Inventory hf;
        try {
            hf = new Inventory(); 
            hf.setLocation(this.getLocation());
        this.dispose();
        hf.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AlterProduct().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bgAP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAlter;
    private javax.swing.JLabel name;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField newPrice;
    private javax.swing.JLabel price;
    private javax.swing.JLabel quant;
    private javax.swing.JSpinner quant1;
    private javax.swing.JLabel save;
    // End of variables declaration//GEN-END:variables
}
