/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.scenes;

import fmm.classesauxiliares.CompradorController;
import static fmm.scenes.AlterPSFrame.vendaA;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 2aimaq20
 */
public class AlterCompSaleFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlterCompSale
     */
    public AlterCompSaleFrame() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png")).getImage());
        nomeComprador.setText(vendaA.comp.getNome());
        telefoneComprador.setText(vendaA.comp.getTelefone());        
        bairroComprador.setText(vendaA.comp.end1.getBairro());
        numComprador.setText(vendaA.comp.end1.getNumero());
        ruaComprador.setText(vendaA.comp.end1.getRua());
        compComprador.setText(vendaA.comp.end1.getComplemento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefoneComprador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bairroComprador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ruaComprador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numComprador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        compComprador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        nomeComprador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bgACS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Sale");
        setMaximumSize(new java.awt.Dimension(739, 459));
        setMinimumSize(new java.awt.Dimension(739, 459));
        setResizable(false);
        getContentPane().setLayout(null);

        telefoneComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telefoneComprador.setToolTipText("Telefone do Comprador");
        getContentPane().add(telefoneComprador);
        telefoneComprador.setBounds(150, 160, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 80, 30);

        bairroComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bairroComprador.setToolTipText("Bairro do Comprador");
        getContentPane().add(bairroComprador);
        bairroComprador.setBounds(150, 210, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bairro:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 60, 30);

        ruaComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ruaComprador.setToolTipText("Rua do Comprador");
        getContentPane().add(ruaComprador);
        ruaComprador.setBounds(150, 260, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rua:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 260, 60, 30);

        numComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numComprador.setToolTipText("Número do Comprador");
        numComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCompradorActionPerformed(evt);
            }
        });
        getContentPane().add(numComprador);
        numComprador.setBounds(150, 310, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nº:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 310, 60, 30);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/save_icon.png"))); // NOI18N
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(530, 340, 60, 64);

        compComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        compComprador.setToolTipText("Complemento referente à localização");
        getContentPane().add(compComprador);
        compComprador.setBounds(150, 360, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Complemento:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 360, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 60, 30);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/volta_icon.png"))); // NOI18N
        back.setToolTipText("Voltar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 20, 64, 64);

        nomeComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeComprador.setToolTipText("Nome do Comprador");
        getContentPane().add(nomeComprador);
        nomeComprador.setBounds(150, 110, 180, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar Comprador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 260, 50);

        bgACS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/bg_tm_right.jpg"))); // NOI18N
        getContentPane().add(bgACS);
        bgACS.setBounds(0, 0, 740, 450);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 60, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCompradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCompradorActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
      int n = JOptionPane.showConfirmDialog(this, "Deseja Alterar os campos mesmo?");
          if(n==0){
              System.out.println("Id: "+AlterPSFrame.vendaA.comp.getId());
            if(CompradorController.alterCompPedingSale(AlterPSFrame.vendaA.comp.getId(),nomeComprador.getText(),telefoneComprador.getText(),bairroComprador.getText(),ruaComprador.getText(), numComprador.getText(),compComprador.getText() )){
                AlterPSFrame aps = new AlterPSFrame();
        
                aps.setLocation(getLocation());

                aps.setVisible(true);

                dispose();
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Não alterado, ocorreu algum erro!","Alerta",0);
            }
          }
          
        
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saveMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
         AlterPSFrame aps = new AlterPSFrame();
        
        aps.setLocation(getLocation());
        
        aps.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterCompSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterCompSaleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextField bairroComprador;
    private javax.swing.JLabel bgACS;
    private javax.swing.JTextField compComprador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeComprador;
    private javax.swing.JTextField numComprador;
    private javax.swing.JTextField ruaComprador;
    private javax.swing.JLabel save;
    private javax.swing.JTextField telefoneComprador;
    // End of variables declaration//GEN-END:variables
}
