/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.scenes;

import fmm.classesauxiliares.*;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author 2aimaq20
 */
public class AlterAccount extends javax.swing.JFrame {
    
    
    /**
     * Creates new form AlterAccount
     */
    public AlterAccount() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png")).getImage());
        newName.setText(AuthFrame.pessoa.getUser());
        save.setToolTipText("Salvar");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newName = new javax.swing.JTextField();
        alertPass = new javax.swing.JLabel();
        lblMss = new javax.swing.JLabel();
        newRepass = new javax.swing.JPasswordField();
        lblRP = new javax.swing.JLabel();
        lblNP = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        back = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        lblNU = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgRP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Sale");
        setMaximumSize(new java.awt.Dimension(739, 459));
        setMinimumSize(new java.awt.Dimension(739, 459));
        setPreferredSize(new java.awt.Dimension(739, 459));
        setResizable(false);
        getContentPane().setLayout(null);

        newName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newName.setToolTipText("Novo nome de usuário");
        getContentPane().add(newName);
        newName.setBounds(130, 150, 170, 40);

        alertPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alertPass.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(alertPass);
        alertPass.setBounds(200, 320, 310, 30);

        lblMss.setText("(mínimo: 8 caracteres máximo: 16 caracteres)");
        getContentPane().add(lblMss);
        lblMss.setBounds(110, 250, 280, 16);
        getContentPane().add(newRepass);
        newRepass.setBounds(380, 270, 170, 40);

        lblRP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRP.setForeground(new java.awt.Color(255, 255, 255));
        lblRP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRP.setText("REESCREVA A SENHA");
        getContentPane().add(lblRP);
        lblRP.setBounds(370, 230, 200, 30);

        lblNP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNP.setForeground(new java.awt.Color(255, 255, 255));
        lblNP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNP.setText("NOVA SENHA");
        getContentPane().add(lblNP);
        lblNP.setBounds(70, 190, 180, 40);
        getContentPane().add(newPass);
        newPass.setBounds(140, 270, 170, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/volta_icon.png"))); // NOI18N
        back.setToolTipText("Voltar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 20, 64, 64);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/save_icon.png"))); // NOI18N
        save.setToolTipText("Salvar");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(320, 360, 60, 64);

        lblNU.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNU.setForeground(new java.awt.Color(255, 255, 255));
        lblNU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNU.setText("NOVO USERNAME");
        getContentPane().add(lblNU);
        lblNU.setBounds(70, 100, 180, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar Conta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 320, 50);

        bgRP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/bg_tm_right.jpg"))); // NOI18N
        getContentPane().add(bgRP);
        bgRP.setBounds(0, 0, 740, 459);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
 
    
    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
         if(!newName.getText().equals("")&& ( new String(newPass.getPassword()).equals(""))){//Altera Username
            String usr = newName.getText();
            
            try {
                ContaController.alterarConta1(usr);
            } catch (ClassNotFoundException|SQLException ex) {
                System.out.println(ex);
            }
            
            
           HomeFrame hf;
        try {
            hf = new HomeFrame(); 
            hf.setLocation(this.getLocation());
        this.dispose();
        hf.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
        }
        else if(newName.getText().equals("")&& ( new String(newPass.getPassword()).equals(""))){//Alter Pass
           
        String p1 = new String(newPass.getPassword());
        String p2 = new String(newRepass.getPassword());
        int num = ContaController.verificaPass(p1,p2);
        
        if(num==0){
              alertPass.setForeground(Color.red);
              alertPass.setText("Senhas não estão entre 8 a 16 caracteres!");
          }
          else if(num==1){
              
              alertPass.setForeground(Color.red);
              alertPass.setText("Senhas não são iguais!");
          }else if(num==2){
                  alertPass.setForeground(Color.red);
              alertPass.setText("<html>Senhas não são iguais!<br>Senhas não estão entre 8 a 16 caracteres!</html>");
          }
          else{
              
              try{
                ContaController.alterarConta2(p2);
              } catch (ClassNotFoundException|SQLException ex) {
                  System.out.println(ex);
              }
           HomeFrame hf;
        try {
            hf = new HomeFrame(); 
            hf.setLocation(this.getLocation());
        this.dispose();
        hf.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
          }
        }
        else{
            String usr = newName.getText();
            String p1 = new String(newPass.getPassword());
        String p2 = new String(newRepass.getPassword());
        int num = ContaController.verificaPass(p1,p2);
        
       if(num==0){
              alertPass.setForeground(Color.red);
              alertPass.setText("Senhas não estão entre 8 a 16 caracteres!");
          }
          else if(num==1){
              
              alertPass.setForeground(Color.red);
              alertPass.setText("Senhas não são iguais!");
          }else if(num==2){
                  alertPass.setForeground(Color.red);
              alertPass.setText("<html>Senhas não são iguais!<br>Senhas não estão entre 8 a 16 caracteres!</html>");
          }
          else{
              
              try{
                ContaController.alterarConta3(usr, p2);
              } catch (ClassNotFoundException|SQLException ex) {
                  System.out.println(ex);
              }
           HomeFrame hf;
        try {
            hf = new HomeFrame(); 
            hf.setLocation(this.getLocation());
        this.dispose();
        hf.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
          }
        }
        
    }//GEN-LAST:event_saveMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        HomeFrame hf;
        try {
            hf = new HomeFrame(); 
            hf.setLocation(this.getLocation());
        this.dispose();
        hf.setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
       back.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_backMouseExited

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
       save.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
       save.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertPass;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bgRP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMss;
    private javax.swing.JLabel lblNP;
    private javax.swing.JLabel lblNU;
    private javax.swing.JLabel lblRP;
    private javax.swing.JTextField newName;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField newRepass;
    private javax.swing.JLabel save;
    // End of variables declaration//GEN-END:variables
}
