/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.scenes;

import fmm.classesauxiliares.Produto;
import fmm.classesauxiliares.ProdutoController;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author 2aimaq20
 */
public class AlterProdSaleFrame extends javax.swing.JFrame {
    private Produto ps;
    private List<Produto> prodS;
    private List<Integer> limite;
    private float vpay;
    
    /**
     * Creates new form AlterProdSaleFrame
     */
    public AlterProdSaleFrame() throws ClassNotFoundException, SQLException {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png")).getImage());
        ps= new Produto();
        
        produtosComboBox.addItem("--Selecione um item--");
        
        ProdutoController.readNameProducts(1);
        prodS = new ArrayList<>();
        prodS = ProdutoController.readProducts();
        limite= new ArrayList<>();
        for(int i=0;i<prodS.size();i++)limite.add(prodS.get(i).getQuant());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produtosComboBox = new javax.swing.JComboBox<>();
        quantSpinner = new javax.swing.JSpinner();
        save = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        unitaryV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgACS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(739, 459));
        setMinimumSize(new java.awt.Dimension(739, 459));
        setPreferredSize(new java.awt.Dimension(739, 459));
        setResizable(false);
        getContentPane().setLayout(null);

        produtosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtosComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(produtosComboBox);
        produtosComboBox.setBounds(110, 110, 190, 30);

        quantSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantSpinnerStateChanged(evt);
            }
        });
        getContentPane().add(quantSpinner);
        quantSpinner.setBounds(130, 160, 100, 30);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/save_icon.png"))); // NOI18N
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(340, 330, 60, 64);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/volta_icon.png"))); // NOI18N
        back.setToolTipText("Voltar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 20, 64, 64);

        unitaryV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unitaryV.setText("Valor Unitário: R$ ");
        getContentPane().add(unitaryV);
        unitaryV.setBounds(320, 110, 330, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Valor a Pagar: R$ ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 170, 330, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantidade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Produto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 70, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar Produto Vendido");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 300, 50);

        bgACS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/bg_tm_right.jpg"))); // NOI18N
        getContentPane().add(bgACS);
        bgACS.setBounds(0, 0, 740, 459);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantSpinnerStateChanged
      if(produtosComboBox.getSelectedIndex()>0){
        if(Integer.valueOf(String.valueOf(quantSpinner.getValue()))<0){
            quantSpinner.setValue(0);
        }else if(Integer.valueOf(String.valueOf(quantSpinner.getValue()))>limite.get(produtosComboBox.getSelectedIndex()-1)){          
            quantSpinner.setValue(limite.get(produtosComboBox.getSelectedIndex()-1));          
        }
        else{
            int n = Integer.valueOf(String.valueOf(quantSpinner.getValue()));
            ps.setQuant(n);
            String txt = "Valor a Pagar: R$ ";
            vpay=n*ps.getPreco();
            
            jLabel5.setText(txt+Float.toString(n*ps.getPreco()));
        }
      }
    }//GEN-LAST:event_quantSpinnerStateChanged

    private void produtosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtosComboBoxActionPerformed
        if(produtosComboBox.getSelectedIndex()!=0){
            ps = prodS.get(produtosComboBox.getSelectedIndex()-1);
            if(ps.getId()==AlterPSFrame.vendaA.prod.getId())limite.set(produtosComboBox.getSelectedIndex()-1,ps.getQuant()+AlterPSFrame.vendaA.getQuant());
            else limite.set(produtosComboBox.getSelectedIndex()-1,ps.getQuant());
            String txt = "Valor Unitário: R$ ";
            unitaryV.setText(txt+Float.toString(ps.getPreco()));
            
        }else{
            String txt = "Valor Unitário: R$ ";
            unitaryV.setText(txt);
            
        }
    }//GEN-LAST:event_produtosComboBoxActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        int n=0;
        
        if(produtosComboBox.getSelectedIndex()>0&&Integer.valueOf(String.valueOf(quantSpinner.getValue()))>0){
        
            try {
            n=ProdutoController.alterProdPedingSale(ps, AlterPSFrame.vendaA.getQuant(), AlterPSFrame.vendaA.getId(), AlterPSFrame.vendaA.getValor_final(), AuthFrame.pessoa.getReceber());
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("erro");
            }
        if(n==1){
        
            AlterPSFrame aps = new AlterPSFrame();
        
            aps.setLocation(getLocation());
        
            aps.setVisible(true);
        
            dispose();
        }else{
            
            javax.swing.JOptionPane.showMessageDialog(this,"Erro ao alterar produto!","Alerta",0);
        }
        }
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saveMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       AlterPSFrame aps = new AlterPSFrame();
        
        aps.setLocation(getLocation());
        
        aps.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterProdSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterProdSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterProdSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterProdSaleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AlterProdSaleFrame().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    System.out.println("erro de tela");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bgACS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JComboBox<String> produtosComboBox;
    private javax.swing.JSpinner quantSpinner;
    private javax.swing.JLabel save;
    private javax.swing.JLabel unitaryV;
    // End of variables declaration//GEN-END:variables
}
