/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.scenes;

import fmm.classesauxiliares.Sale;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Ian Marcony
 */
public class AlterPSFrame extends javax.swing.JFrame {
    public static Sale vendaA;
    /**
     * Creates new form AlterPSFrame
     */
    public AlterPSFrame() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png")).getImage());
        //Comprador
        
        nomeComprador1.setText(vendaA.comp.getNome());
        telefoneComprador1.setText(vendaA.comp.getTelefone());
        bairroComprador1.setText(vendaA.comp.end1.getBairro());
        numComprador1.setText(vendaA.comp.end1.getNumero());
        ruaComprador1.setText(vendaA.comp.end1.getRua());
        compComprador1.setText(vendaA.comp.end1.getComplemento());
      
        //Produto        
        nomeProduto1.setText(vendaA.prod.getNome());
        precoProduto1.setText(precoProduto1.getText()+Float.toString(vendaA.prod.getPreco()));
        quantProduto1.setText(Integer.toString(vendaA.getQuant()));
        payVenda1.setText(Float.toString(vendaA.getValor_final()));
        dcVenda1.setText(vendaA.getDataAtual().toString());
        dpVenda1.setText(vendaA.getDataPay().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcVenda2 = new javax.swing.JLabel();
        dpVenda1 = new javax.swing.JTextField();
        dcVenda1 = new javax.swing.JTextField();
        quantProduto1 = new javax.swing.JTextField();
        payVenda1 = new javax.swing.JTextField();
        precoProduto1 = new javax.swing.JTextField();
        nomeComprador2 = new javax.swing.JLabel();
        nomeProduto1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        compComprador1 = new javax.swing.JTextArea();
        numComprador1 = new javax.swing.JTextField();
        bairroComprador1 = new javax.swing.JTextField();
        ruaComprador1 = new javax.swing.JTextField();
        telefoneComprador1 = new javax.swing.JTextField();
        nomeComprador1 = new javax.swing.JTextField();
        ruaComprador = new javax.swing.JLabel();
        nomeComprador = new javax.swing.JLabel();
        quantProduto = new javax.swing.JLabel();
        precoProduto = new javax.swing.JLabel();
        telefoneComprador = new javax.swing.JLabel();
        dcVenda = new javax.swing.JLabel();
        payVenda = new javax.swing.JLabel();
        complementoComprador = new javax.swing.JLabel();
        btnAlterProd = new javax.swing.JButton();
        btnAlterComp = new javax.swing.JButton();
        numComprador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bairroComprador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgPSF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Sale");
        setMaximumSize(new java.awt.Dimension(739, 459));
        setMinimumSize(new java.awt.Dimension(739, 459));
        setPreferredSize(new java.awt.Dimension(739, 459));
        setResizable(false);
        getContentPane().setLayout(null);

        dcVenda2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dcVenda2.setText("Data para pagar:   ");
        getContentPane().add(dcVenda2);
        dcVenda2.setBounds(480, 270, 104, 20);

        dpVenda1.setEditable(false);
        getContentPane().add(dpVenda1);
        dpVenda1.setBounds(580, 270, 100, 30);

        dcVenda1.setEditable(false);
        getContentPane().add(dcVenda1);
        dcVenda1.setBounds(370, 270, 100, 30);

        quantProduto1.setEditable(false);
        getContentPane().add(quantProduto1);
        quantProduto1.setBounds(160, 270, 100, 30);

        payVenda1.setEditable(false);
        payVenda1.setText("R$");
        getContentPane().add(payVenda1);
        payVenda1.setBounds(510, 220, 170, 30);

        precoProduto1.setEditable(false);
        precoProduto1.setText("R$");
        getContentPane().add(precoProduto1);
        precoProduto1.setBounds(290, 220, 130, 30);

        nomeComprador2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeComprador2.setText("Nome: ");
        getContentPane().add(nomeComprador2);
        nomeComprador2.setBounds(20, 220, 40, 20);

        nomeProduto1.setEditable(false);
        getContentPane().add(nomeProduto1);
        nomeProduto1.setBounds(70, 220, 170, 30);

        compComprador1.setEditable(false);
        compComprador1.setColumns(20);
        compComprador1.setRows(5);
        jScrollPane2.setViewportView(compComprador1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 130, 310, 60);

        numComprador1.setEditable(false);
        getContentPane().add(numComprador1);
        numComprador1.setBounds(280, 110, 70, 30);

        bairroComprador1.setEditable(false);
        getContentPane().add(bairroComprador1);
        bairroComprador1.setBounds(70, 120, 170, 30);

        ruaComprador1.setEditable(false);
        getContentPane().add(ruaComprador1);
        ruaComprador1.setBounds(540, 70, 70, 30);

        telefoneComprador1.setEditable(false);
        getContentPane().add(telefoneComprador1);
        telefoneComprador1.setBounds(310, 74, 170, 30);

        nomeComprador1.setEditable(false);
        getContentPane().add(nomeComprador1);
        nomeComprador1.setBounds(70, 80, 170, 30);

        ruaComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ruaComprador.setText("Rua:");
        getContentPane().add(ruaComprador);
        ruaComprador.setBounds(500, 80, 30, 20);

        nomeComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeComprador.setText("Nome: ");
        getContentPane().add(nomeComprador);
        nomeComprador.setBounds(20, 80, 40, 20);

        quantProduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quantProduto.setText("Quantidade Comprada:");
        getContentPane().add(quantProduto);
        quantProduto.setBounds(20, 270, 130, 20);

        precoProduto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        precoProduto.setText("Preço:");
        getContentPane().add(precoProduto);
        precoProduto.setBounds(250, 220, 40, 20);

        telefoneComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telefoneComprador.setText("Telefone: ");
        getContentPane().add(telefoneComprador);
        telefoneComprador.setBounds(250, 80, 60, 20);

        dcVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dcVenda.setText("Data da Compra:   ");
        getContentPane().add(dcVenda);
        dcVenda.setBounds(270, 270, 103, 20);

        payVenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        payVenda.setText("Valor A Pagar:");
        getContentPane().add(payVenda);
        payVenda.setBounds(430, 220, 80, 20);

        complementoComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        complementoComprador.setText("Complemento:");
        getContentPane().add(complementoComprador);
        complementoComprador.setBounds(360, 110, 100, 20);

        btnAlterProd.setBackground(new java.awt.Color(153, 255, 51));
        btnAlterProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterProd.setText("Alterar Produto Vendido");
        btnAlterProd.setToolTipText("Vai para alteração do produto");
        btnAlterProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterProdMouseExited(evt);
            }
        });
        btnAlterProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterProd);
        btnAlterProd.setBounds(20, 370, 210, 40);

        btnAlterComp.setBackground(new java.awt.Color(153, 255, 51));
        btnAlterComp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterComp.setText("Alterar Dados do Comprador");
        btnAlterComp.setToolTipText("Vai para a alteração do comprador");
        btnAlterComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterCompMouseExited(evt);
            }
        });
        btnAlterComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterCompActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterComp);
        btnAlterComp.setBounds(500, 370, 206, 40);

        numComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        numComprador.setText("Nº:");
        getContentPane().add(numComprador);
        numComprador.setBounds(250, 110, 20, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html><u style=\"color: black;\">Produto</u></html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 70, 20);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/volta_icon.png"))); // NOI18N
        back.setToolTipText("Voltar");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(640, 20, 64, 64);

        bairroComprador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bairroComprador.setText("Bairro: ");
        getContentPane().add(bairroComprador);
        bairroComprador.setBounds(20, 120, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html><u style=\"color: black;\">Comprador</u></html>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 70, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sobre a Venda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 330, 60);

        bgPSF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/bg_tm_right.jpg"))); // NOI18N
        getContentPane().add(bgPSF);
        bgPSF.setBounds(0, 0, 740, 459);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterProdActionPerformed
        AlterProdSaleFrame acs;
        try {
            acs = new AlterProdSaleFrame();
            acs.setLocation(getLocation());
        acs.setVisible(true);
        dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("erro");
        }
        
    }//GEN-LAST:event_btnAlterProdActionPerformed

    private void btnAlterCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterCompActionPerformed
        AlterCompSaleFrame acs = new AlterCompSaleFrame();
        acs.setLocation(getLocation());
        acs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAlterCompActionPerformed

    private void btnAlterProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterProdMouseEntered
        btnAlterProd.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAlterProdMouseEntered

    private void btnAlterProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterProdMouseExited
        btnAlterProd.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAlterProdMouseExited

    private void btnAlterCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterCompMouseEntered
        btnAlterComp.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAlterCompMouseEntered

    private void btnAlterCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterCompMouseExited
        btnAlterComp.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnAlterCompMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        PedingSaleFrame ps;
        try {
            ps = new PedingSaleFrame();
            ps.setLocation(getLocation());
       ps.setVisible(true);
       dispose();
        } catch (Exception ex) {
            System.out.println("erro");
        }
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterPSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterPSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterPSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterPSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterPSFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bairroComprador;
    private javax.swing.JTextField bairroComprador1;
    private javax.swing.JLabel bgPSF;
    private javax.swing.JButton btnAlterComp;
    private javax.swing.JButton btnAlterProd;
    private javax.swing.JTextArea compComprador1;
    private javax.swing.JLabel complementoComprador;
    private javax.swing.JLabel dcVenda;
    private javax.swing.JTextField dcVenda1;
    private javax.swing.JLabel dcVenda2;
    private javax.swing.JTextField dpVenda1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeComprador;
    private javax.swing.JTextField nomeComprador1;
    private javax.swing.JLabel nomeComprador2;
    private javax.swing.JTextField nomeProduto1;
    private javax.swing.JLabel numComprador;
    private javax.swing.JTextField numComprador1;
    private javax.swing.JLabel payVenda;
    private javax.swing.JTextField payVenda1;
    private javax.swing.JLabel precoProduto;
    private javax.swing.JTextField precoProduto1;
    private javax.swing.JLabel quantProduto;
    private javax.swing.JTextField quantProduto1;
    private javax.swing.JLabel ruaComprador;
    private javax.swing.JTextField ruaComprador1;
    private javax.swing.JLabel telefoneComprador;
    private javax.swing.JTextField telefoneComprador1;
    // End of variables declaration//GEN-END:variables
}
