/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmm.scenes;


import fmm.classesauxiliares.Salesman;
import fmm.classesauxiliares.SalesmanController;
import java.awt.Cursor;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;


/**
 *
 * @author Ian Marcony
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() throws ClassNotFoundException, SQLException {
        initComponents();
       setIconImage(new ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png")).getImage());
            AuthFrame.pessoa.setReceber(SalesmanController.totalPendencias());
            AuthFrame.pessoa.setTotal(SalesmanController.totalVendas());
        totalVendas.setText(Float.toString(SalesmanController.totalVendas()));
        valorReceber.setText(Float.toString(SalesmanController.totalPendencias()));
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save1 = new javax.swing.JLabel();
        sale5 = new javax.swing.JLabel();
        sale4 = new javax.swing.JLabel();
        sale3 = new javax.swing.JLabel();
        sale2 = new javax.swing.JLabel();
        sale1 = new javax.swing.JLabel();
        sale = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorReceber = new javax.swing.JTextArea();
        totalVendas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        bgHF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy Sale");
        setMaximumSize(new java.awt.Dimension(740, 459));
        setMinimumSize(new java.awt.Dimension(740, 459));
        setPreferredSize(new java.awt.Dimension(740, 459));
        setResizable(false);
        getContentPane().setLayout(null);

        save1.setBackground(new java.awt.Color(255, 255, 255));
        save1.setForeground(new java.awt.Color(255, 255, 255));
        save1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/user_update_icon.png"))); // NOI18N
        save1.setToolTipText("Alterar Dados da Conta");
        save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                save1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                save1MouseExited(evt);
            }
        });
        getContentPane().add(save1);
        save1.setBounds(520, 360, 64, 64);

        sale5.setBackground(new java.awt.Color(255, 255, 255));
        sale5.setForeground(new java.awt.Color(255, 255, 255));
        sale5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/caixa_icon.png"))); // NOI18N
        sale5.setToolTipText("Caixa");
        sale5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sale5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sale5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sale5MouseExited(evt);
            }
        });
        getContentPane().add(sale5);
        sale5.setBounds(60, 310, 80, 64);

        sale4.setBackground(new java.awt.Color(255, 255, 255));
        sale4.setForeground(new java.awt.Color(255, 255, 255));
        sale4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/estoque_icon.png"))); // NOI18N
        sale4.setToolTipText("Estoque");
        sale4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sale4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sale4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sale4MouseExited(evt);
            }
        });
        getContentPane().add(sale4);
        sale4.setBounds(250, 310, 80, 64);

        sale3.setBackground(new java.awt.Color(255, 255, 255));
        sale3.setForeground(new java.awt.Color(255, 255, 255));
        sale3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/addProduto_icon.png"))); // NOI18N
        sale3.setToolTipText("Registrar Produto");
        sale3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sale3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sale3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sale3MouseExited(evt);
            }
        });
        getContentPane().add(sale3);
        sale3.setBounds(250, 230, 80, 64);

        sale2.setBackground(new java.awt.Color(255, 255, 255));
        sale2.setForeground(new java.awt.Color(255, 255, 255));
        sale2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/salePendentes_icon.png"))); // NOI18N
        sale2.setToolTipText("Vendas Pendentes");
        sale2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sale2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sale2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sale2MouseExited(evt);
            }
        });
        getContentPane().add(sale2);
        sale2.setBounds(60, 230, 80, 64);

        sale1.setBackground(new java.awt.Color(255, 255, 255));
        sale1.setForeground(new java.awt.Color(255, 255, 255));
        sale1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/historico_icon.png"))); // NOI18N
        sale1.setToolTipText("Historico de Vendas");
        sale1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sale1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sale1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sale1MouseExited(evt);
            }
        });
        getContentPane().add(sale1);
        sale1.setBounds(250, 150, 64, 64);

        sale.setBackground(new java.awt.Color(255, 255, 255));
        sale.setForeground(new java.awt.Color(255, 255, 255));
        sale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/addSale_icon.png"))); // NOI18N
        sale.setToolTipText("Vender");
        sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleMouseExited(evt);
            }
        });
        getContentPane().add(sale);
        sale.setBounds(60, 150, 80, 64);

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/sair_icon.png"))); // NOI18N
        save.setToolTipText("Sair da Conta");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(640, 360, 64, 64);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/logo_EasySale.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(540, 0, 200, 200);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("<html>Valor total a receber das vendas pendentes<br>           R$</html>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 30, 270, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Área de trabalho");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 120, 150, 40);

        valorReceber.setEditable(false);
        valorReceber.setColumns(20);
        valorReceber.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        valorReceber.setRows(5);
        valorReceber.setText("\n");
        valorReceber.setToolTipText("Total a receber");
        getContentPane().add(valorReceber);
        valorReceber.setBounds(290, 50, 190, 50);

        totalVendas.setEditable(false);
        totalVendas.setColumns(20);
        totalVendas.setFont(new java.awt.Font("Monospaced", 1, 28)); // NOI18N
        totalVendas.setRows(5);
        totalVendas.setText("\n");
        totalVendas.setToolTipText("Total de ganhos");
        getContentPane().add(totalVendas);
        totalVendas.setBounds(30, 50, 190, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("<html>Total obtido nas vendas<br>           R$</html>");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 250, 40);

        bgHF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fmm/assets/bg_tm_right.jpg"))); // NOI18N
        getContentPane().add(bgHF);
        bgHF.setBounds(0, 0, 740, 459);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
         AuthFrame af = new AuthFrame();
        af.setLocation(this.getLocation());
        af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveMouseClicked

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saveMouseExited

    private void saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseClicked
         SelectSaleFrame ps ;
         ps = new SelectSaleFrame();
         ps.setLocationRelativeTo(null);
         dispose();
         ps.setVisible(true);
    }//GEN-LAST:event_saleMouseClicked

    private void saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseEntered
       sale.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saleMouseEntered

    private void saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseExited
       sale.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_saleMouseExited

    private void sale1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale1MouseClicked
       HistoricoVendasFrame hv;
        try {
            hv = new HistoricoVendasFrame();
            hv.setLocation(this.getLocation());
            hv.setVisible(true);
            this.dispose(); 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sale1MouseClicked

    private void sale1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale1MouseEntered
         sale1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sale1MouseEntered

    private void sale1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale1MouseExited
        sale1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_sale1MouseExited

    private void sale2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale2MouseClicked
        // TODO add your handling code here:try {
         try{
             PedingSaleFrame ps;
            ps = new PedingSaleFrame();
            ps.setLocation(getLocation());
            dispose();
            ps.setVisible(true);
        } catch (Exception ex) {
            System.out.println("erro");
        }
    }//GEN-LAST:event_sale2MouseClicked

    private void sale2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale2MouseEntered
        sale2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sale2MouseEntered

    private void sale2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale2MouseExited
        sale2.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_sale2MouseExited

    private void sale3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale3MouseClicked
       RegisterProduct rp = new RegisterProduct();
        rp.setLocation(this.getLocation());
        this.dispose();
        rp.setVisible(true);
    }//GEN-LAST:event_sale3MouseClicked

    private void sale3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale3MouseEntered
         sale3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sale3MouseEntered

    private void sale3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale3MouseExited
          sale3.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_sale3MouseExited

    private void sale4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale4MouseClicked
         Inventory iv;
        try {
            iv = new Inventory();
            iv.setLocation(this.getLocation());
        this.dispose();
        iv.setVisible(true);
        } catch (ClassNotFoundException|SQLException ex) {
                            System.out.println(ex);
                        }
    }//GEN-LAST:event_sale4MouseClicked

    private void sale4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale4MouseEntered
          sale4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sale4MouseEntered

    private void sale4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale4MouseExited
        sale4.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_sale4MouseExited

    private void sale5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale5MouseClicked
        CashFrame ps;
        
      
                      try {
                           ps = new CashFrame();
                           ps.setLocation(getLocation());
                        dispose();
                         ps.setVisible(true);
                       } catch (ClassNotFoundException|SQLException ex) {
                            System.out.println(ex);
                        } catch (ParseException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sale5MouseClicked

    private void sale5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale5MouseEntered
        sale5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_sale5MouseEntered

    private void sale5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sale5MouseExited
        sale5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_sale5MouseExited

    private void save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseClicked
         AlterAccount aa = new AlterAccount();
        aa.setLocation(this.getLocation());
        dispose();
        aa.setVisible(true);
    }//GEN-LAST:event_save1MouseClicked

    private void save1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseEntered
        save1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_save1MouseEntered

    private void save1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save1MouseExited
       save1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_save1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new HomeFrame().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgHF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel sale;
    private javax.swing.JLabel sale1;
    private javax.swing.JLabel sale2;
    private javax.swing.JLabel sale3;
    private javax.swing.JLabel sale4;
    private javax.swing.JLabel sale5;
    private javax.swing.JLabel save;
    private javax.swing.JLabel save1;
    private javax.swing.JTextArea totalVendas;
    private javax.swing.JTextArea valorReceber;
    // End of variables declaration//GEN-END:variables
}
